mysql:
  container_name: flow-dashboard-mysql
  image: mysql:5.6.23
  restart: always
  ports:
    - "31307:3306"
  environment:
       TZ : "Asia/Shanghai"
       MYSQL_ROOT_PASSWORD: qazplm123!
       MYSQL_DATABASE: flow_dashboard_db
  command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
